# Setup
title:               MicroPython for BeagleConnect Freedom
tagline:             'GSoC 2021'
description:         'MicroPython for BeagleConnect Freedom'
url:                 "https://yadnik1.github.io"
baseurl:             '/myblog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yadnik Bendale
  url:               https://www.linkedin.com/in/yadnik-bendale-aa709b1a5/
  email:             yadnik22@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
